environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35
init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"
  - "ECHO %APPVEYOR_REPO_TAG_NAME%"
install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"   
  - conda update --yes conda
  - conda create -y -q -n test-environment python=%PYTHON_VERSION%
  - activate test-environment
  - python setup.py develop
test_script:
  - pytest
# build is done in build_script
build: off
build_script:
  # build exe file using pyinstaller from main run script
  - IF "%PYTHON_VERSION%"=="3.5" (
      pip install pyinstaller &&
      pyinstaller --onefile --windowed --name=auxiclean_windows run.py
    )     
artifacts:
  - path: dist/auxiclean_windows.exe
    name: auxiclean_windows

# deploy only when making a new release on master branch
# the windows build will be uploaded into the new release.
deploy:
  appveyor_repo_tag: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  relsease: $(APPVEYOR_REPO_TAG_NAME)
  description: ""
  provider: GitHub
  force_update: false
  auth_token:
    secure: x2ous7RX857j64h4DSkiEBCSU8kUQYCL31UBrPLUSgosixVS/XDXGA6TWr0DLPm9
  artifact: auxiclean_windows
  on:
    branch: 
      - master
      - test_deploy
    appveyor_repo_tag: true
    PYTHON_VERSION: 3.5
