matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - source $HOME/miniconda/bin/activate
        - conda update --yes conda
        - conda create -q --yes -n test-environment python=3.6
        - source activate test-environment
    - language: python
      os: linux
      python: 3.6
      after_success:
        - pip install coveralls
        - coveralls
install:
  - python setup.py develop
script:
  - python tests.py
branches:
  only:
  - master
  - develop
